# Import Tools

In [1]:
###Modules Utilized 
import sklearn
import nltk
import numpy as np
import pandas as pd
from pycaret.classification import *
from pycaret.datasets import get_data
from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer, CountVectorizer

# Load Data

In [2]:
#data used to train the supervised models in milestone 2
data = pd.read_parquet('supervised_learning_data')

In [3]:
#data = data.sample(frac=0.5, replace=True, random_state=1)

#binary classification
data = data[data.sentiment != 1]

data = data.rename(columns={"pre_process": "review",
                             "sentiment": "Flag_1"})
data.head()

                                              review  Flag_1
0  engrossing page turner race class bullying gra...       2
1  interesting debut “ hello niveus high it ’ s t...       2
2             wow ordered book teenage daughter luvs       2
3  definitely ya novel great plot childish charac...       2
4  timely book engrossing story intrigued premise...       2

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337148 entries, 0 to 362923
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   review  337148 non-null  object
 1   Flag_1  337148 non-null  int64
dtypes: int64(1), object(1)
memory usage: 7.7+ MB

# Vectorize Data

Sklearn provides facilities to extract numerical features from a text document by tokenizing, counting and normalising. CountVectorizer performs the task of tokenizing and counting, while TfidfTransformer normalizes the data. TfidfVectorizer, on the other hand, performs all three operations, thereby streamlining the process of natural language processing.

### Create Dataframe

In [5]:
#Set vectorizers
%time v = TfidfVectorizer(max_features=800, ngram_range=(1, 4))
%time V = v.fit_transform(data['review'])

df_tf = pd.DataFrame(V.toarray(), columns=v.vocabulary_)
#display(df_tf.head())

CPU times: user 11 µs, sys: 9 µs, total: 20 µs
Wall time: 23.8 µs
CPU times: user 3min, sys: 11.2 s, total: 3min 11s
Wall time: 3min 12s

In [6]:
#Preparing processed and BoW-TF embedded data for Classification
df_tf_m = pd.concat([data, df_tf], axis = 1)
df_tf_m.drop(columns=['review'], inplace = True)
print(df_tf_m.shape)
#df_tf_m.head()

(361528, 800)

In [7]:
df_tf_m = df_tf_m.dropna()

# Supervised Learning Set-Up

### Initiate Pipeline

In [8]:
#build models using data
%time s = setup(df_tf_m, target = 'Flag_1', feature_selection = True, fix_imbalance=True,train_size = 0.80,session_id = 5)

CPU times: user 16min 39s, sys: 48.4 s, total: 17min 28s
Wall time: 1min 52s

In [9]:
%time best_models = compare_models(n_select = 3)
save_model(best_models[0] , 'bestmodel1')
save_model(best_models[1] , 'bestmodel2')
save_model(best_models[2] , 'bestmodel3')

CPU times: user 36min 38s, sys: 2min 59s, total: 39min 38s
Wall time: 54min 18s
Transformation Pipeline and Model Successfully Saved
Transformation Pipeline and Model Successfully Saved
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                  LGBMClassifier(boosting_type='gbdt', class_weight=None,
                                 colsample_bytree=1.0, importance_type='split',
                                 learning_rate=0.1, max_depth=-1,
                                 min_child_samples=20, min_child_weight=0.001,
                                 min_split_gain=0.0, n_estimators=100, n_jobs=-1,
                                 num_leaves=31, objective=None, random_state=5,
                                 reg_alpha=0.0, reg_lambda=0.0, silent='warn',
                                 subsample=1.0, subsample_for_bin=200000,
                                 subsample_freq=0))],
          verbose=False),
 'bestmodel3.pkl')

In [10]:
%time ensemble_et = ensemble_model(best_models[0])
save_model(ensemble_et , 'ensemble_et')

CPU times: user 8min 18s, sys: 1min 8s, total: 9min 27s
Wall time: 26min 14s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                                   max_leaf_nodes=None,
                                                                   max_samples=None,
                                                                   min_impurity_decrease=0.0,
                                                                   min_samples_leaf=1,
                                                                   min_samples_split=2,
                                                                   min_weight_fraction_leaf=0.0,
                                                                   n_estimators=100,
                                                                   n_jobs=-1,
                                                                   oob_score=False,
                                                                   random_state=5,
                                                                   verbose=0,
                                                                   warm_start=False),
                                    max_features=1.0, max_samples=1.0,
                                    n_estimators=10, n_jobs=None,
                                    oob_score=False, random_state=5, verbose=0,
                                    warm_start=False))],
          verbose=False),
 'ensemble_et.pkl')

In [11]:
%time ensemble_rf = ensemble_model(best_models[1])
save_model(ensemble_rf , 'ensemble_rf')

CPU times: user 7min 6s, sys: 52.9 s, total: 7min 59s
Wall time: 15min 39s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                                     max_leaf_nodes=None,
                                                                     max_samples=None,
                                                                     min_impurity_decrease=0.0,
                                                                     min_samples_leaf=1,
                                                                     min_samples_split=2,
                                                                     min_weight_fraction_leaf=0.0,
                                                                     n_estimators=100,
                                                                     n_jobs=-1,
                                                                     oob_score=False,
                                                                     random_state=5,
                                                                     verbose=0,
                                                                     warm_start=False),
                                    max_features=1.0, max_samples=1.0,
                                    n_estimators=10, n_jobs=None,
                                    oob_score=False, random_state=5, verbose=0,
                                    warm_start=False))],
          verbose=False),
 'ensemble_rf.pkl')

In [12]:
%time ensemble_lgbm = ensemble_model(best_models[2])
save_model(ensemble_lgbm , 'ensemble_lgbm')

CPU times: user 24min 10s, sys: 25.1 s, total: 24min 35s
Wall time: 6min 8s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                             min_child_samples=20,
                                                             min_child_weight=0.001,
                                                             min_split_gain=0.0,
                                                             n_estimators=100,
                                                             n_jobs=-1,
                                                             num_leaves=31,
                                                             objective=None,
                                                             random_state=5,
                                                             reg_alpha=0.0,
                                                             reg_lambda=0.0,
                                                             silent='warn',
                                                             subsample=1.0,
                                                             subsample_for_bin=200000,
                                                             subsample_freq=0),
                                    max_features=1.0, max_samples=1.0,
                                    n_estimators=10, n_jobs=None,
                                    oob_score=False, random_state=5, verbose=0,
                                    warm_start=False))],
          verbose=False),
 'ensemble_lgbm.pkl')

In [13]:
%time blender_weighted_med = blend_models(best_models, weights = [0.50,0.30,0.20])
save_model(blender_weighted_med , 'blender_weighted_med')

CPU times: user 8min 16s, sys: 1min, total: 9min 17s
Wall time: 11min 13s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                               learning_rate=0.1,
                                                               max_depth=-1,
                                                               min_child_samples=20,
                                                               min_child_weight=0.001,
                                                               min_split_gain=0.0,
                                                               n_estimators=100,
                                                               n_jobs=-1,
                                                               num_leaves=31,
                                                               objective=None,
                                                               random_state=5,
                                                               reg_alpha=0.0,
                                                               reg_lambda=0.0,
                                                               silent='warn',
                                                               subsample=1.0,
                                                               subsample_for_bin=200000,
                                                               subsample_freq=0))],
                                   flatten_transform=True, n_jobs=-1,
                                   verbose=False, voting='soft',
                                   weights=[0.5, 0.3, 0.2]))],
          verbose=False),
 'blender_weighted_med.pkl')

In [14]:
%time blender_weighted_soft = blend_models(best_models, weights = [0.50,0.30,0.20], method='soft')
save_model(blender_weighted_soft , 'blender_weighted_soft')

CPU times: user 6min 19s, sys: 59 s, total: 7min 18s
Wall time: 10min 59s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                               learning_rate=0.1,
                                                               max_depth=-1,
                                                               min_child_samples=20,
                                                               min_child_weight=0.001,
                                                               min_split_gain=0.0,
                                                               n_estimators=100,
                                                               n_jobs=-1,
                                                               num_leaves=31,
                                                               objective=None,
                                                               random_state=5,
                                                               reg_alpha=0.0,
                                                               reg_lambda=0.0,
                                                               silent='warn',
                                                               subsample=1.0,
                                                               subsample_for_bin=200000,
                                                               subsample_freq=0))],
                                   flatten_transform=True, n_jobs=-1,
                                   verbose=False, voting='soft',
                                   weights=[0.5, 0.3, 0.2]))],
          verbose=False),
 'blender_weighted_soft.pkl')

In [15]:
%time stacker = stack_models(best_models)
save_model(stacker , 'stacker')

CPU times: user 10min 52s, sys: 2min 24s, total: 13min 16s
Wall time: 43min 59s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                                 subsample_for_bin=200000,
                                                                 subsample_freq=0))],
                                     final_estimator=LogisticRegression(C=1.0,
                                                                        class_weight=None,
                                                                        dual=False,
                                                                        fit_intercept=True,
                                                                        intercept_scaling=1,
                                                                        l1_ratio=None,
                                                                        max_iter=1000,
                                                                        multi_class='auto',
                                                                        n_jobs=None,
                                                                        penalty='l2',
                                                                        random_state=5,
                                                                        solver='lbfgs',
                                                                        tol=0.0001,
                                                                        verbose=0,
                                                                        warm_start=False),
                                     n_jobs=-1, passthrough=True,
                                     stack_method='auto', verbose=0))],
          verbose=False),
 'stacker.pkl')

In [18]:
%time stacker_et = stack_models(best_models, meta_model = best_models[0])
save_model(stacker , 'stacker_et')

CPU times: user 20min, sys: 1min 35s, total: 21min 35s
Wall time: 45min 10s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                                 subsample_for_bin=200000,
                                                                 subsample_freq=0))],
                                     final_estimator=LogisticRegression(C=1.0,
                                                                        class_weight=None,
                                                                        dual=False,
                                                                        fit_intercept=True,
                                                                        intercept_scaling=1,
                                                                        l1_ratio=None,
                                                                        max_iter=1000,
                                                                        multi_class='auto',
                                                                        n_jobs=None,
                                                                        penalty='l2',
                                                                        random_state=5,
                                                                        solver='lbfgs',
                                                                        tol=0.0001,
                                                                        verbose=0,
                                                                        warm_start=False),
                                     n_jobs=-1, passthrough=True,
                                     stack_method='auto', verbose=0))],
          verbose=False),
 'stacker_et.pkl')

In [19]:
%time blender_weighted_hard = blend_models(best_models, weights = [0.50,0.30,0.20], method='hard')
save_model(blender_weighted_hard , 'blender_weighted_hard')

CPU times: user 4min 54s, sys: 1min 33s, total: 6min 28s
Wall time: 11min 48s
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['page', 'race', 'class', 'ive',
                                              'never', 'fan', 'girl', 'book',
                                              'series', 'enjoyed', 'get', 'isnt',
                                              'favorite', 'however',
                                              'incredibly', 'awesom...
                                                               learning_rate=0.1,
                                                               max_depth=-1,
                                                               min_child_samples=20,
                                                               min_child_weight=0.001,
                                                               min_split_gain=0.0,
                                                               n_estimators=100,
                                                               n_jobs=-1,
                                                               num_leaves=31,
                                                               objective=None,
                                                               random_state=5,
                                                               reg_alpha=0.0,
                                                               reg_lambda=0.0,
                                                               silent='warn',
                                                               subsample=1.0,
                                                               subsample_for_bin=200000,
                                                               subsample_freq=0))],
                                   flatten_transform=True, n_jobs=-1,
                                   verbose=False, voting='hard',
                                   weights=[0.5, 0.3, 0.2]))],
          verbose=False),
 'blender_weighted_hard.pkl')